/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

public class App {
    public String getGreeting() {
        return "Olá mundo!";
    }

    public static void main(String[] args) {
        
         //Comentário de linha
        
        /*
            Minha primeira linha de comentário
            Segunda linha de comentáro...
        */
        
        /**
         * Comentário de documentação
         */
        
        System.out.println(new App().getGreeting());
        System.out.println("Meu segundo comando de saída");
        
       
    }
}
