algoritmo "Aula 3.H - Aleatório"

var

i, aleatorioMaximo, aleatorioMinimo, incremento : inteiro

inicio

repita
aleatorio 1,100
         leia(aleatorioMaximo)
         leia(aleatorioMinimo)
aleatorio off

ate aleatorioMaximo >= aleatorioMinimo
limpatela

aleatorio 1,5
leia(incremento)
aleatorio off
limpatela

para i de aleatorioMinimo ate aleatorioMaximo passo incremento FACA
     escreval(i)
fimpara

fimalgoritmo
